version: "3.5"

volumes:
  smtp_relay:

secrets:
  smtp_relay_admin_password:
    name: ${STACK_NAME:-technocore}_smtp_relay_admin_password
    external: true

services:
  ## Uncomment this if Traefik will be used for routing traffick to this service.
  #ingress:
  #  networks:
  #    - smtp_relay

  smtp_relay:
    #override the default command with one that stores smtp credentials, since the image doesn't do this natively
    command: '/bin/bash -c "echo $$POSTFIX_relayhost $$relayhost_username:$$relayhost_passwd > /etc/postfix/sasl/sasl_passwd && /usr/sbin/postmap /etc/postfix/sasl/sasl_passwd && /root/run"'
    deploy:
      labels:
        - com.ouroboros.enable=true
      mode: global
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
      # Big services will need this modified or removed.
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    environment:
      # Sometimes you have to pass in ${DOMAIN} to enable the correct link paths to be generated.
      # Othertimes you can use http:// or https:// for the website. Weird trick.
      - ADMIN_USER=${ADMIN_USER}
      #if you use mailgun, you cannot use your duckdns domain, it will not validate it
      - POSTFIX_myhostname=${REGISTERED_DOMAIN:?Please copy template.env to .env and provide provide a value for REGISTERED_DOMAIN}
      #reluctantly adding 192.168.0.0/16 to allowed networks.  This address range is typically used on routers and, if the mail relay
      #port were mapped to the host, this would be a HUGE security risk (anyone could send email through the relay, including others
      #on the same router).  The "expose" section, as I understand it only makes the port available to other docker services
      #and does not map it to the host, which is the only reason why I think its ok to allow the 192.168.0.0/16 range, otherwise
      #you can't use the mail relay after you've exhausted the private addresses 172.16.0.0-> 172.31.0.0 with many services on your
      #stack
      - "POSTFIX_mynetworks=127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128 172.0.0.0/8 192.168.0.0/16"
      - POSTFIX_mydestination=${REGISTERED_DOMAIN:?Please copy template.env to .env and provide provide a value for REGISTERED_DOMAIN},localhost
      - POSTFIX_smtp_tls_security_level=may
      - POSTFIX_smtpd_tls_security_level=none
      - POSTFIX_smtp_sasl_auth_enable=yes
      - "POSTFIX_smtp_sasl_password_maps=hash:/etc/postfix/sasl/sasl_passwd"
      - POSTFIX_smtp_sasl_security_options=noanonymous
      - POSTFIX_relayhost=${UPSTREAM_SMTP_HOST:?Please copy template.env to .env and provide provide a value for UPSTREAM_SMTP_HOST}
      - relayhost_username=${UPSTREAM_SMTP_USERNAME:?Please copy template.env to .env and provide provide a value for UPSTREAM_SMTP_USERNAME}
      - relayhost_passwd=${UPSTREAM_SMTP_PASSWORD:?Please copy template.env to .env and provide provide a value for UPSTREAM_SMTP_PASSWORD}
      - POSTFIX_smtp_tls_CAfile=/etc/ssl/certs/ca-certificates.crt #might need to change if not on Debian-based linux, uesd to validate secure connection to SMTP
      - POSTFIX_smtp_tls_note_starttls_offer=yes
      - POSTFIX_smtp_use_tls=yes
    # Not sure if this is needed.
    #hostname: smtp_relay
    image: mwader/postfix-relay:latest
    #image: ${image_provider:-scififarms}/technocore-smtp_relay:${TAG:-latest}
    logging:
      driver: "${LOGGING_DRIVER}"
      options:
        tag: "{{.Name}}"
    #secrets:
    #  - source: smtp_relay_smtp_relay_db_password
    #    target: smtp_relay_db_password
    volumes:
      # Likely need to change this
      - smtp_relay:/var/lib/smtp_relay
      - ${DEV_MOUNT_SMTP_RELAY_SHELL_MIGRATIONS:-$EMPTY_MOUNT}
      - mail-relay-lib-postfix:/var/lib/postfix
      - mail-relay-mail:/var/mail
      - mail-relay-spool-postfix:/var/spool/postfix
      - mail-relay-opendkim-keys:/etc/opendkim/keys
      - mail-relay-sasl:/etc/postfix/sasl
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro #use host's CAs to validate remote SMTP certs, may need to change if not on debian-based linux

