version: "3.5"

volumes:
  smtp_relay:

secrets:
  smtp_relay_smtp_password:
    name: ${STACK_NAME:-technocore}_smtp_relay_smtp_password
    external: true

services:

  smtp_relay:
    deploy:
      labels:
        - com.ouroboros.enable=true
      mode: global
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
      # Big services will need this modified or removed.
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    environment:
      - HOSTNAME=smtp_relay
      - RELAYHOST=${TECHNOCORE_SMTP_HOST}:587
      - RELAYHOST_USERNAME=${TECHNOCORE_SMTP_USERNAME}
      - RELAYHOST_PASSWORD={{"{{DOCKER-SECRET:smtp_password}}"}}
      - ALLOWED_SENDER_DOMAINS=${TECHNOCORE_SMTP_ALLOWED_DOMAINS}
      - TZ=${TZ}
    image: ${image_provider:-scififarms}/technocore-smtp-relay:${TAG:-latest}
    logging:
      driver: "${LOGGING_DRIVER}"
      options:
        tag: "{{.Name}}"
    secrets:
      - source: smtp_relay_smtp_password
        target: smtp_password
