version: "3.5"

volumes:
  smtp_relay:
  smtp_relay-db:

secrets:
  smtp_relay_admin_password:
    name: ${STACK_NAME:-technocore}_smtp_relay_admin_password
    external: true
  smtp_relay_smtp_relay-db_password:
    name: ${STACK_NAME:-technocore}_smtp_relay_smtp_relay-db_password
    external: true

services:
  ## Uncomment this if Traefik will be used for routing traffick to this service.
  #ingress:
  #  networks:
  #    - smtp_relay

  smtp_relay:
    deploy:
      labels:
      #  - traefik.frontend.rule=$SMTP_RELAY_ROUTING_LABEL
      #  - traefik.frontend.priority=$SMTP_RELAY_ROUTING_LABEL_PRIORITY
      #  - traefik.port=SET_ME_PLEASE
      #  - ${TRAEFIK_BASIC_AUTH}
      #  - traefik.enable=true
      #  # You'll need to set applicaiton's port here.
      #  - traefik.tags=ingress 
      #  - traefik.docker.network=${STACK_NAME:-technocore}_smtp_relay
      #  # Traefik service that listens to HTTP
      #  - traefik.redirectorservice.frontend.entryPoints=http
      #  - traefik.redirectorservice.frontend.redirect.entryPoint=https
      #  # Traefik service that listens to HTTPS
      #  - traefik.webservice.frontend.entryPoints=https
        - com.ouroboros.enable=true
      mode: global
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
      # Big services will need this modified or removed.
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    environment:
      # Sometimes you have to pass in ${DOMAIN} to enable the correct link paths to be generated.
      # Othertimes you can use http:// or https:// for the website. Weird trick.
      - ADMIN_USER=${ADMIN_USER}
    image: ${image_provider:-scififarms}/technocore-smtp_relay:${TAG:-latest}
    logging:
      driver: "${LOGGING_DRIVER}"
      options:
        tag: "{{.Name}}"
    #networks:
    #  - smtp_relay
    #  - smtp_relay-private
    #secrets:
    #  - source: smtp_relay_smtp_relay_db_password
    #    target: smtp_relay_db_password
    volumes:
      # Likely need to change this
      - smtp_relay:/var/lib/smtp_relay
      - ${DEV_MOUNT_SMTP_RELAY_SHELL_MIGRATIONS:-$EMPTY_MOUNT}
